
language: java

jdk:
    - oraclejdk8
    - oraclejdk7
branches:
    except:
    only:
        - master


notifications:
  email:
    recipients:
      - j3239192001@gmail.com
    on_success: always
    on_failure: always
script:
    - javac -d . -cp junit-4.12.jar *.java
    - java ntou.cs.sorter.MySorterMain
    - java -cp .:junit-4.12.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore
     ntou.cs.sorter.MySorterTest
